name: CI
on:
  push:

jobs:
  main:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.18'
            erlang: '27.3.4'
            lint: true
          - elixir: '1.17'
            erlang: '26.2.5.12'
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.erlang }}
          elixir-version: ${{ matrix.elixir }}
      - run: mix deps.get --check-locked
      - run: mix format --check-formatted
        if: ${{ matrix.lint }}
      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}
      - run: mix compile --warnings-as-errors
      - run: mix test
